version: '1.0.{build}'

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37

install:
- pip install tox
- pip install pyinstaller

build_script:
- pyinstaller evolvesaveeditor.py

# before_package:
#- 7z a EvolveSaveEditor.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\dist\evolvesaveeditor

test_script:
- tox

artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\dist\evolvesaveeditor
    name: EvolveSaveEditor.%APPVEYOR_BUILD_VERSION%