version: '{build}'

environment:
  matrix:
  - NAME: "deploy"
    PYTHON: "C:\\Python37-x64"
    PYTHON_ARCH: "64"
    PYTHON_VERSION: 3.7
    DEPLOY_SCENARIO: true
  - NAME: "py37x64_test"
    PYTHON: "C:\\Python37-x64"
    TOXENV: py37
    PYTHON_ARCH: "64"
    PYTHON_VERSION: 3.7
    DEPLOY_SCENARIO: false
  - NAME: "py37x32_test"
    PYTHON: "C:\\Python37"
    TOXENV: py37
    PYTHON_ARCH: "32"
    PYTHON_VERSION: 3.7
    DEPLOY_SCENARIO: false

init:
- ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- python --version
- python -c "import sys, platform, struct;
  print(sys.platform, platform.machine(), struct.calcsize('P')*8)"
- python -m pip install --upgrade pip

build: off

for:
-
  # don't run all the tests on just a tag
  matrix:
    only:
      - DEPLOY_SCENARIO: false

  skip_tags: true

  before_test:
    - python -m pip install tox

  test_script:
    - tox

-
  # only run build & deploy steps on a tag
  matrix:
    only:
      - DEPLOY_SCENARIO: true

  skip_non_tags: true

  before_build:
    - python -m pip install -r requirements.txt

  build_script:
  - pyinstaller evolvesaveeditor.py
  - 7z a EvolveSaveEditor.win.x%PYTHON_ARCH%.%APPVEYOR_REPO_TAG_NAME%.zip %APPVEYOR_BUILD_FOLDER%\dist\evolvesaveeditor

  artifacts:
  - path: "EvolveSaveEditor.*.zip"
    name: EvolveSaveEditor
    type: zip

  deploy:
    release: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub
    auth_token:
      secure: 34Em9/uFMIFZ46PjwPebWEqUpOhblu2q1+M9CrPP15/mUWpgBoip0V42tO0movB+
    artifact: /EvolveSaveEditor.*.zip/
    prerelease: false
    draft: false
    on:
      APPVEYOR_REPO_TAG: true