version: '1.0.{build}'

environment:
  matrix:
  - PYTHON: "C:\\Python37-x64"
    TOXENV: py37
    PYTHON_ARCH: "64"
    PYTHON_VERSION: 3.7
  - PYTHON: "C:\\Python37"
    TOXENV: py37
    PYTHON_ARCH: "32"
    PYTHON_VERSION: 3.7
  - PYTHON: "C:\\Python36-x64"
    TOXENV: py36
    PYTHON_ARCH: "64"
    PYTHON_VERSION: 3.6
  - PYTHON: "C:\\Python36"
    TOXENV: py36
    PYTHON_ARCH: "32"
    PYTHON_VERSION: 3.6

init:
- ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- python --version
- python -c "import sys, platform, struct;
  print(sys.platform, platform.machine(), struct.calcsize('P')*8)"
- python -m pip install tox
- python -m pip install pyinstaller

build_script:
- pyinstaller evolvesaveeditor.py

test_script:
- tox

before_package:
- 7z a EvolveSaveEditor.x%PYTHON_ARCH%.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\dist\evolvesaveeditor

artifacts:
- path: "EvolveSaveEditor.*.zip"
  name: EvolveSaveEditor
  type: zip